source:      .
destination: ./_site
includes:    ./_includes
baseurl: /

title: Songyang Ruan
url: http://Horatioj.github.io
github_repo: https://github.com/Horatioj/Horatioj.github.io.git

collections:
  projects:
    output: true
